### PR TITLE
Updating editor class to atom-text-editor

### PR DESCRIPTION
**Pull request by arnaudsj**
This will fix issues:
    \* https://github.com/colindean/atom-zenburn/issues/2
    \* https://github.com/colindean/atom-zenburn/issues/5

### CODE REVIEW

**Comment by colindean** [comment]
Thank you!

**Comment by colindean** [comment]
I'm see a regression, here.

screen shot 2015-02-20 at 9 48 57 am

I'm on Atom 0.181.

**Comment by colindean** [comment]
Confirmed. Rolled back to 1.0.2 and it looks normal...

screen shot 2015-02-20 at 9 51 39 am

Can you look into it? I won't really have time for a few days.

**Comment by arnaudsj** [comment]
Yes, sorry I fixed it. It was a typo :) Sending you a new pull request.

**Comment by arnaudsj** [comment]
@colindean this fixes it: https://github.com/colindean/atom-zenburn/pull/7

**Pull request merged**
